# Generated by Django 3.0.3 on 2020-06-13 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='toppings_no',
        ),
    ]
