# Generated by Django 3.0.3 on 2020-06-13 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_page', '0002_remove_food_toppings_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='price',
        ),
    ]
